spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SEProject
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181
  address: localhost